/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AppOptions {
  /**
   * Имя приложения
   */
  name: string;
  /**
   * Нужно ли запустить установку зависимостей
   */
  install?: boolean;
  /**
   * Путь до папки, в которую нужно будет сгенерировать приложение
   */
  path?: string;
  [k: string]: unknown;
}
