/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ComponentOptions {
    /**
     * Имя компонента
     */
    name: string;
    /**
     * Путь до папки, в которую нужно будет сгенерирован компонент
     */
    path?: string;
    style: string;
    [k: string]: unknown;
}
